name: sehatin
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.0.0 # Tambahkan ini untuk package dio
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat.regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts/Montserrat-VariableFont_wght.ttf
